add root euid checks to cbddisks start and stop

diff --git a/system/cbddisks_start.tmpl b/system/cbddisks_start.tmpl
--- a/system/cbddisks_start.tmpl
+++ b/system/cbddisks_start.tmpl
@@ -57,24 +57,35 @@ main () {
         exit 1
     fi
 
+    if [ "\$(id -u)" -ne "0" ]; then
+        >&2 echo "\$0: error - must be run as root"
+        exit 1
+    fi
+
     if [ "x\$IS_SYSTEMD" = "xyes" ]; then
         if ! systemctl daemon-reload 2>/dev/null; then
-            echo "Must be run as root"
+            >&2 echo "\$0: error - unable to issue systemctl daemon-reload"
             exit 1
         fi
 
         if [ "x\$all" = "xyes" ]; then
-            systemctl start cbdsetup.target
-            exit \$?
+            if ! systemctl start cbdsetup.target; then
+                >&2 echo "\$0: error - failed to start cbdsetup.target"
+                exit 1
+            fi
+            exit 0
         else
             for cbd in \$cbds; do
-                systemctl start cbdsetup@"\$cbd".service || exit 1
+                if ! systemctl start "cbdsetup@\${cbd}.service"; then
+                    >&2 echo "\$0: error - failed to start cbdsetup@\${cbd}.service"
+                    exit 1
+                fi
             done
             exit 0
         fi
     else
         if ! ulimit -l unlimited 2>/dev/null; then
-            echo "Must be run as root"
+            >&2 echo "\$0: error - failed to set ulimit -l (max locked memory)"
             exit 1
         fi
 
diff --git a/system/cbddisks_stop.tmpl b/system/cbddisks_stop.tmpl
--- a/system/cbddisks_stop.tmpl
+++ b/system/cbddisks_stop.tmpl
@@ -56,6 +56,11 @@ main () {
         exit 1
     fi
 
+    if [ "\$(id -u)" -ne "0" ]; then
+        >&2 echo "\$0: error - must be run as root"
+        exit 1
+    fi
+
     do_stop \$cbds
     exit \$?
 }
