adjust wording of cbdtab sanity check errors

diff --git a/system/cbdsetup.functions.tmpl b/system/cbdsetup.functions.tmpl
--- a/system/cbdsetup.functions.tmpl
+++ b/system/cbdsetup.functions.tmpl
@@ -39,21 +39,24 @@ check_systemd_cbdtab () {
     while read -r NBD CBD OPTS; do
         [ -z "\$NBD" ] && continue;
 
-        if [ "x\$NBD" = "x" ] || [ "x\$CBD" = "x" ] ||
-            ! expr "x\$NBD" : 'xnbd[[:digit:]]\+' >/dev/null ||
-            ! expr "x\$CBD" : 'x[[:alnum:]_-]\+:[[:alnum:]_-]\+' >/dev/null; then
-            log_warning_msg "WARNING: cbdtab invalid line ('\$NBD' '\$CBD')... skipping"
+        if ! expr "x\$NBD" : 'xnbd[[:digit:]]\+' >/dev/null; then
+            log_warning_msg "WARNING: cbdtab has invalid nbd '\$NBD'"
+            continue
+        fi
+
+        if [ "x\$CBD" = "x" ] || ! expr "x\$CBD" : 'x[[:alnum:]_-]\+:[[:alnum:]_-]\+' >/dev/null; then
+            log_warning_msg "WARNING: cbdtab has invalid remote:disk '\$CBD'"
             continue
         fi
 
         if [ "x\$(eval "echo \\\$\$NBD")" = "x1" ]; then
-            log_warning_msg "WARNING: cbdtab duplicate nbd device found ('\$NBD')... skipping"
+            log_warning_msg "WARNING: cbdtab has duplicate nbd '\$NBD'"
             continue
         fi
 
         CBDx="\$(echo "\$CBD" | sed 's/://')"
         if [ "x\$(eval "echo \\\$\$CBDx")" = "x1" ]; then
-            log_warning_msg "WARNING: cbdtab duplicate remote:disk found ('\$CBD')... skipping"
+            log_warning_msg "WARNING: cbdtab has duplicate remote:disk '\$CBD'"
             continue
         fi
 
